### ISSUE TITLE
Update to newer version

### ISSUE THREAD

**Issue by LSTANCZYK** [KrzysztofKielce/xaf-updater-improved#1]
Are you planning on updating this tool for newer versions of DevExpress? 

If not than can you please elaborate on what you mean by __On newer XAF versions this tool needs to be manually merged with the original DevExpress.ExpressApp.Updater.exe source code.__

**Comment by ChrisNeedSpace** [comment]
Hi Łukasz, nice to hear from you.
I will update the project as soon as I can.

**Comment by ChrisNeedSpace** [comment]
The project should now support versions 17.2-19.1.

Cheers,
Krzys
