### ISSUE TITLE
Suggestion: copy only newer files

### ISSUE THREAD

**Issue by vimarx** [KrzysztofKielce/xaf-updater-improved#2]
Hi, we do many updates per week, and most of then , only changes a small subset of files. I would be desirable to update only changed / new files.

Thanks
Gustavo

**Comment by ChrisNeedSpace** [comment]
Hi, nice to hear someone uses this repo!
Can you clarify what you mean? Would you prefer to have a single folder in this repository and when a new version is added, just branch/tag them within the same set of files?

**Comment by vimarx** [comment]
Hi, I'm was referring a suggestion for the updater functionality, to update only changed files instead of copying all files.
In some of my customers, this copies takes about 500 megabytes or more, and sometimes, updating several clients at the same moment, generates a bandwidth bottleneck

**Comment by ChrisNeedSpace** [comment]
Ah, right, good idea. However, I cannot provide you any ETA when or if I code that. 
Any pull requests would be very helpful, though.

**Comment by vimarx** [comment]
ok, no rush ...

**Comment by ChrisNeedSpace** [comment]
Hi, sorry for a very late reply. Please check if the pushed update works for you.
